version: '3' 
services: 
  nginx: 
    image: nginx 
    ports: 
      - "8080:80" 
    volumes: 
      - ./nginx/my-nginx.conf:/etc/nginx/conf.d/default.conf
  html_app: 
    build: 
      context: ./html_app 
    ports: 
     - "3001:80"

  my_app: 
    image: project1-html_app 
    ports: 
      - "8004:80"  
      - "8003:80"  
    networks: 
      test_network: 
        ipv4_address: 10.10.1.86
      test_network_2:
        ipv4_address: 10.10.1.90
networks: 
  test_network: 
    driver: bridge 
    ipam: 
      config: 
        - subnet: 10.10.1.0/24
  test_network_2: 
    driver: bridge 
    ipam:
      config: 
        - subnet: 10.10.1.0/24
